import type {
  Subject,
  StudySession,
  Task,
  Exam,
  Quiz,
  QuizAttempt,
  RevisionNote,
  PracticeQuestion,
  SavedResource,
} from '@/types';

// Helper to get today's date and offset
function dateOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

const today = new Date();
const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export const subjects: Subject[] = [
  {
    id: 'sub-math',
    name: 'Mathematics',
    color: 'blue',
    icon: 'Calculator',
    topics: [
      { id: 'top-algebra', name: 'Algebra', completed: true },
      { id: 'top-geometry', name: 'Geometry', completed: true },
      { id: 'top-trig', name: 'Trigonometry', completed: true },
      { id: 'top-calc', name: 'Calculus', completed: false },
      { id: 'top-stats', name: 'Statistics', completed: false },
    ],
  },
  {
    id: 'sub-phys',
    name: 'Physics',
    color: 'purple',
    icon: 'Atom',
    topics: [
      { id: 'top-mech', name: 'Mechanics', completed: true },
      { id: 'top-waves', name: 'Waves & Optics', completed: true },
      { id: 'top-elec', name: 'Electricity & Magnetism', completed: false },
      { id: 'top-thermo', name: 'Thermodynamics', completed: false },
    ],
  },
  {
    id: 'sub-chem',
    name: 'Chemistry',
    color: 'green',
    icon: 'FlaskConical',
    topics: [
      { id: 'top-atomic', name: 'Atomic Structure', completed: true },
      { id: 'top-bonding', name: 'Chemical Bonding', completed: true },
      { id: 'top-organic', name: 'Organic Chemistry', completed: false },
      { id: 'top-reactions', name: 'Chemical Reactions', completed: false },
    ],
  },
  {
    id: 'sub-bio',
    name: 'Biology',
    color: 'teal',
    icon: 'Dna',
    topics: [
      { id: 'top-cells', name: 'Cell Biology', completed: true },
      { id: 'top-genetics', name: 'Genetics', completed: false },
      { id: 'top-ecology', name: 'Ecology', completed: false },
      { id: 'top-human', name: 'Human Physiology', completed: false },
    ],
  },
  {
    id: 'sub-eng',
    name: 'English Literature',
    color: 'orange',
    icon: 'BookOpen',
    topics: [
      { id: 'top-shake', name: 'Shakespeare', completed: true },
      { id: 'top-poetry', name: 'Poetry Analysis', completed: false },
      { id: 'top-novel', name: 'Modern Novel', completed: false },
    ],
  },
  {
    id: 'sub-hist',
    name: 'History',
    color: 'pink',
    icon: 'Landmark',
    topics: [
      { id: 'top-ww2', name: 'World War II', completed: true },
      { id: 'top-cold', name: 'Cold War', completed: false },
      { id: 'top-civil', name: 'Civil Rights Movement', completed: false },
    ],
  },
];

export const studySessions: StudySession[] = [
  {
    id: 'ses-1',
    subjectId: 'sub-math',
    topicId: 'top-calc',
    title: 'Calculus: Differentiation Rules',
    date: dateOffset(0),
    startTime: '09:00',
    endTime: '10:30',
    day: dayNames[today.getDay()],
    completed: false,
    notes: 'Focus on chain rule and product rule',
  },
  {
    id: 'ses-2',
    subjectId: 'sub-phys',
    topicId: 'top-elec',
    title: 'Electric Circuits Practice',
    date: dateOffset(0),
    startTime: '11:00',
    endTime: '12:00',
    day: dayNames[today.getDay()],
    completed: false,
  },
  {
    id: 'ses-3',
    subjectId: 'sub-chem',
    topicId: 'top-organic',
    title: 'Organic Chemistry: Functional Groups',
    date: dateOffset(0),
    startTime: '14:00',
    endTime: '15:30',
    day: dayNames[today.getDay()],
    completed: true,
  },
  {
    id: 'ses-4',
    subjectId: 'sub-bio',
    topicId: 'top-genetics',
    title: 'Genetics: Mendelian Inheritance',
    date: dateOffset(1),
    startTime: '09:00',
    endTime: '10:00',
    day: dayNames[(today.getDay() + 1) % 7],
    completed: false,
  },
  {
    id: 'ses-5',
    subjectId: 'sub-eng',
    topicId: 'top-poetry',
    title: 'Poetry Analysis: Romantic Era',
    date: dateOffset(1),
    startTime: '10:30',
    endTime: '12:00',
    day: dayNames[(today.getDay() + 1) % 7],
    completed: false,
  },
  {
    id: 'ses-6',
    subjectId: 'sub-math',
    topicId: 'top-stats',
    title: 'Statistics: Probability Distributions',
    date: dateOffset(2),
    startTime: '13:00',
    endTime: '14:30',
    day: dayNames[(today.getDay() + 2) % 7],
    completed: false,
  },
  {
    id: 'ses-7',
    subjectId: 'sub-hist',
    topicId: 'top-cold',
    title: 'Cold War: Key Events Timeline',
    date: dateOffset(3),
    startTime: '15:00',
    endTime: '16:00',
    day: dayNames[(today.getDay() + 3) % 7],
    completed: false,
  },
  {
    id: 'ses-8',
    subjectId: 'sub-phys',
    topicId: 'top-thermo',
    title: 'Thermodynamics: Laws & Applications',
    date: dateOffset(4),
    startTime: '10:00',
    endTime: '11:30',
    day: dayNames[(today.getDay() + 4) % 7],
    completed: false,
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Complete Calculus Problem Set 4',
    description: 'Questions 1-15 on differentiation techniques',
    subjectId: 'sub-math',
    dueDate: dateOffset(2),
    priority: 'high',
    completed: false,
    type: 'homework',
  },
  {
    id: 'task-2',
    title: 'Lab Report: Circuit Analysis',
    description: 'Write up findings from Tuesday\'s lab session',
    subjectId: 'sub-phys',
    dueDate: dateOffset(5),
    priority: 'high',
    completed: false,
    type: 'assignment',
  },
  {
    id: 'task-3',
    title: 'Read Chapter 8: Organic Reactions',
    subjectId: 'sub-chem',
    dueDate: dateOffset(1),
    priority: 'medium',
    completed: false,
    type: 'reading',
  },
  {
    id: 'task-4',
    title: 'Essay: Themes in Modern Poetry',
    description: '1500 words comparing two Romantic poets',
    subjectId: 'sub-eng',
    dueDate: dateOffset(7),
    priority: 'medium',
    completed: false,
    type: 'project',
  },
  {
    id: 'task-5',
    title: 'Genetics Worksheet',
    subjectId: 'sub-bio',
    dueDate: dateOffset(0),
    priority: 'high',
    completed: true,
    type: 'homework',
  },
  {
    id: 'task-6',
    title: 'Cold War Timeline Project',
    description: 'Create visual timeline of key Cold War events',
    subjectId: 'sub-hist',
    dueDate: dateOffset(10),
    priority: 'low',
    completed: false,
    type: 'project',
  },
  {
    id: 'task-7',
    title: 'Review Statistics Notes',
    subjectId: 'sub-math',
    dueDate: dateOffset(3),
    priority: 'low',
    completed: false,
    type: 'reading',
  },
];

export const exams: Exam[] = [
  {
    id: 'exam-1',
    subjectId: 'sub-math',
    title: 'Mathematics Mock Exam',
    date: dateOffset(14),
    time: '09:00',
    location: 'Hall A',
    notes: 'Covers all topics. Calculator permitted.',
  },
  {
    id: 'exam-2',
    subjectId: 'sub-phys',
    title: 'Physics Final Exam',
    date: dateOffset(21),
    time: '13:00',
    location: 'Hall B',
    notes: 'Mechanics, Waves, Electricity, Thermodynamics',
  },
  {
    id: 'exam-3',
    subjectId: 'sub-chem',
    title: 'Chemistry Mid-term',
    date: dateOffset(7),
    time: '10:00',
    location: 'Lab 3',
  },
  {
    id: 'exam-4',
    subjectId: 'sub-bio',
    title: 'Biology Practical',
    date: dateOffset(28),
    time: '14:00',
    location: 'Science Lab',
  },
];

export const quizzes: Quiz[] = [
  {
    id: 'quiz-1',
    subjectId: 'sub-math',
    title: 'Algebra Fundamentals',
    description: 'Test your understanding of equations, inequalities, and functions.',
    difficulty: 'easy',
    questions: [
      {
        id: 'q1',
        question: 'What is the solution to 2x + 5 = 17?',
        options: ['x = 4', 'x = 6', 'x = 8', 'x = 12'],
        correctIndex: 1,
        explanation: '2x + 5 = 17 → 2x = 12 → x = 6',
      },
      {
        id: 'q2',
        question: 'Which of these is a quadratic equation?',
        options: ['y = 3x + 2', 'y = x² + 5x + 6', 'y = 1/x', 'y = √x'],
        correctIndex: 1,
        explanation: 'A quadratic equation has the form ax² + bx + c = 0, where a ≠ 0.',
      },
      {
        id: 'q3',
        question: 'Factorise: x² - 9',
        options: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', '(x-9)(x+1)'],
        correctIndex: 2,
        explanation: 'This is a difference of squares: a² - b² = (a-b)(a+b). So x² - 9 = (x-3)(x+3).',
      },
      {
        id: 'q4',
        question: 'What is the slope of y = 4x - 7?',
        options: ['7', '4', '-7', '-4'],
        correctIndex: 1,
        explanation: 'In y = mx + c form, m is the slope. Here m = 4.',
      },
      {
        id: 'q5',
        question: 'Solve: 3(x - 2) = 12',
        options: ['x = 4', 'x = 6', 'x = 8', 'x = 10'],
        correctIndex: 1,
        explanation: '3(x-2) = 12 → x-2 = 4 → x = 6',
      },
    ],
  },
  {
    id: 'quiz-2',
    subjectId: 'sub-phys',
    title: 'Mechanics Basics',
    description: 'Newton\'s laws, motion, forces, and energy.',
    difficulty: 'medium',
    questions: [
      {
        id: 'q1',
        question: 'What is the SI unit of force?',
        options: ['Joule', 'Watt', 'Newton', 'Pascal'],
        correctIndex: 2,
        explanation: 'Force is measured in Newtons (N), named after Isaac Newton. 1 N = 1 kg·m/s².',
      },
      {
        id: 'q2',
        question: 'Which law states that for every action there is an equal and opposite reaction?',
        options: ['First Law', 'Second Law', 'Third Law', 'Law of Gravitation'],
        correctIndex: 2,
        explanation: 'Newton\'s Third Law: For every action, there is an equal and opposite reaction.',
      },
      {
        id: 'q3',
        question: 'What is the acceleration due to gravity on Earth (approx)?',
        options: ['8.8 m/s²', '9.8 m/s²', '10.8 m/s²', '11.2 m/s²'],
        correctIndex: 1,
        explanation: 'Standard gravity is approximately 9.8 m/s² at Earth\'s surface.',
      },
      {
        id: 'q4',
        question: 'Kinetic energy is calculated as:',
        options: ['KE = mgh', 'KE = ½mv²', 'KE = mv', 'KE = Fd'],
        correctIndex: 1,
        explanation: 'Kinetic energy = ½ × mass × velocity². The energy of motion.',
      },
      {
        id: 'q5',
        question: 'If a 2kg object accelerates at 3 m/s², what net force acts on it?',
        options: ['3 N', '5 N', '6 N', '9 N'],
        correctIndex: 2,
        explanation: 'F = ma → F = 2 kg × 3 m/s² = 6 N',
      },
    ],
  },
  {
    id: 'quiz-3',
    subjectId: 'sub-chem',
    title: 'Atomic Structure',
    description: 'Protons, neutrons, electrons, and atomic models.',
    difficulty: 'easy',
    questions: [
      {
        id: 'q1',
        question: 'What is the atomic number of Carbon?',
        options: ['4', '6', '8', '12'],
        correctIndex: 1,
        explanation: 'Carbon has 6 protons, giving it an atomic number of 6.',
      },
      {
        id: 'q2',
        question: 'Which subatomic particle has no charge?',
        options: ['Proton', 'Electron', 'Neutron', 'Positron'],
        correctIndex: 2,
        explanation: 'Neutrons are electrically neutral — they have no charge.',
      },
      {
        id: 'q3',
        question: 'Where are electrons found in an atom?',
        options: ['In the nucleus', 'In electron shells/orbitals', 'Mixed with protons', 'Only in the outermost layer'],
        correctIndex: 1,
        explanation: 'Electrons occupy energy levels (shells) around the nucleus.',
      },
      {
        id: 'q4',
        question: 'What does the mass number represent?',
        options: ['Number of protons', 'Number of electrons', 'Protons + neutrons', 'Protons - electrons'],
        correctIndex: 2,
        explanation: 'Mass number = number of protons + number of neutrons in the nucleus.',
      },
    ],
  },
  {
    id: 'quiz-4',
    subjectId: 'sub-bio',
    title: 'Cell Biology',
    description: 'Cell structure, organelles, and cellular processes.',
    difficulty: 'medium',
    questions: [
      {
        id: 'q1',
        question: 'Which organelle is known as the powerhouse of the cell?',
        options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi apparatus'],
        correctIndex: 1,
        explanation: 'Mitochondria produce ATP through cellular respiration — the cell\'s energy currency.',
      },
      {
        id: 'q2',
        question: 'What process do plant cells use to make food?',
        options: ['Respiration', 'Photosynthesis', 'Digestion', 'Fermentation'],
        correctIndex: 1,
        explanation: 'Photosynthesis converts light energy into chemical energy (glucose) in chloroplasts.',
      },
      {
        id: 'q3',
        question: 'Which structure controls what enters and leaves the cell?',
        options: ['Cell wall', 'Cytoplasm', 'Cell membrane', 'Nucleus'],
        correctIndex: 2,
        explanation: 'The cell membrane is selectively permeable, controlling what passes in and out.',
      },
      {
        id: 'q4',
        question: 'What is the genetic material in cells?',
        options: ['RNA', 'DNA', 'Protein', 'Lipid'],
        correctIndex: 1,
        explanation: 'DNA (deoxyribonucleic acid) carries the genetic instructions for life.',
      },
    ],
  },
];

export const quizAttempts: QuizAttempt[] = [
  {
    id: 'att-1',
    quizId: 'quiz-1',
    score: 4,
    total: 5,
    date: dateOffset(-3),
    answers: [1, 1, 2, 1, 1],
  },
  {
    id: 'att-2',
    quizId: 'quiz-1',
    score: 5,
    total: 5,
    date: dateOffset(-1),
    answers: [1, 1, 2, 1, 1],
  },
  {
    id: 'att-3',
    quizId: 'quiz-3',
    score: 3,
    total: 4,
    date: dateOffset(-5),
    answers: [1, 2, 1, 2],
  },
];

export const revisionNotes: RevisionNote[] = [
  {
    id: 'rn-1',
    subjectId: 'sub-math',
    topicId: 'top-algebra',
    title: 'Algebra: Key Rules and Formulas',
    content:
      'Algebra is the branch of mathematics that uses letters and symbols to represent numbers and quantities in equations and formulas. Mastering algebraic manipulation is essential for all higher mathematics.\n\nThe fundamental principle of algebra is balance: whatever you do to one side of an equation, you must do to the other. This keeps the equation true as you work toward solving for the unknown variable.',
    keyPoints: [
      'A linear equation has the form y = mx + c, where m is the gradient and c is the y-intercept',
      'When expanding brackets, multiply each term inside by the term outside: a(b + c) = ab + ac',
      'Factorising is the reverse of expanding — look for common factors first',
      'The quadratic formula: x = (-b ± √(b² - 4ac)) / 2a',
      'Difference of squares: a² - b² = (a-b)(a+b)',
      'Always collect like terms to simplify expressions',
    ],
  },
  {
    id: 'rn-2',
    subjectId: 'sub-math',
    topicId: 'top-trig',
    title: 'Trigonometry: Ratios and Identities',
    content:
      'Trigonometry relates the angles and sides of triangles. The three primary trigonometric ratios — sine, cosine, and tangent — are defined in terms of the sides of a right-angled triangle.\n\nThese ratios extend beyond triangles to describe periodic phenomena like waves, sound, and light. Understanding the unit circle helps visualise how these functions behave for any angle, not just those between 0° and 90°.',
    keyPoints: [
      'SOH CAH TOA: sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent',
      'Pythagorean identity: sin²θ + cos²θ = 1',
      'The unit circle has radius 1, centred at the origin',
      'Angles can be measured in degrees or radians (π radians = 180°)',
      'Sine and cosine repeat every 360° (periodic functions)',
    ],
  },
  {
    id: 'rn-3',
    subjectId: 'sub-phys',
    topicId: 'top-mech',
    title: 'Newton\'s Laws of Motion',
    content:
      'Sir Isaac Newton formulated three fundamental laws that describe the relationship between a body and the forces acting upon it. These laws form the foundation of classical mechanics and are still used to describe most everyday motion.\n\nNewton\'s laws apply to objects moving at speeds much less than the speed of light and at scales larger than atoms. For extreme speeds or tiny scales, Einstein\'s relativity and quantum mechanics take over.',
    keyPoints: [
      'First Law (Inertia): An object at rest stays at rest, an object in motion stays in motion, unless acted on by a net force',
      'Second Law: F = ma — Force equals mass times acceleration',
      'Third Law: For every action, there is an equal and opposite reaction',
      'Momentum is conserved in a closed system with no external forces',
      'Weight is the force of gravity on an object: W = mg',
    ],
  },
  {
    id: 'rn-4',
    subjectId: 'sub-phys',
    topicId: 'top-waves',
    title: 'Waves: Properties and Behaviour',
    content:
      'Waves transfer energy from one point to another without transferring matter. They can be mechanical (requiring a medium) or electromagnetic (traveling through a vacuum). Understanding wave behaviour is crucial in physics, from sound and light to modern telecommunications.\n\nAll waves share key properties — amplitude, wavelength, frequency, and speed — and exhibit behaviours like reflection, refraction, diffraction, and interference.',
    keyPoints: [
      'Wave speed = frequency × wavelength (v = fλ)',
      'Transverse waves oscillate perpendicular to direction of travel (e.g., light)',
      'Longitudinal waves oscillate parallel to direction of travel (e.g., sound)',
      'Reflection: angle of incidence = angle of reflection',
      'Refraction: waves change speed and direction when entering a different medium',
      'Diffraction: waves spread out when passing through a gap or around an obstacle',
    ],
  },
  {
    id: 'rn-5',
    subjectId: 'sub-chem',
    topicId: 'top-atomic',
    title: 'Atomic Structure and the Periodic Table',
    content:
      'All matter is made of atoms. Each atom consists of a small, dense nucleus containing protons (positively charged) and neutrons (neutral), surrounded by electrons (negatively charged) in energy levels or shells.\n\nThe number of protons — the atomic number — determines which element an atom is. The arrangement of electrons determines how elements react and bond, which is reflected in the structure of the periodic table.',
    keyPoints: [
      'Atomic number = number of protons (defines the element)',
      'Mass number = protons + neutrons',
      'Electrons fill shells in order: 2, 8, 8, 18...',
      'Isotopes are atoms of the same element with different numbers of neutrons',
      'Group number (for main groups) = number of outer shell electrons',
      'Period number = number of electron shells',
    ],
  },
  {
    id: 'rn-6',
    subjectId: 'sub-chem',
    topicId: 'top-bonding',
    title: 'Chemical Bonding: Ionic, Covalent, and Metallic',
    content:
      'Atoms bond to achieve a full outer shell of electrons, making them more stable. There are three main types of bonding: ionic, covalent, and metallic. Each type gives the resulting substance distinct physical and chemical properties.\n\nThe type of bond formed depends on whether atoms are metals or non-metals, and how they transfer or share electrons to achieve stability.',
    keyPoints: [
      'Ionic bonding: metal loses electrons to non-metal, forming positive and negative ions held by electrostatic attraction',
      'Covalent bonding: two non-metals share pairs of electrons',
      'Metallic bonding: positive metal ions in a sea of delocalised electrons',
      'Ionic compounds have high melting points and conduct when molten or dissolved',
      'Covalent compounds can be simple molecular (low melting point) or giant covalent (high melting point)',
      'Metals are malleable, ductile, and good conductors of heat and electricity',
    ],
  },
  {
    id: 'rn-7',
    subjectId: 'sub-bio',
    topicId: 'top-cells',
    title: 'Cell Structure and Function',
    content:
      'The cell is the basic unit of life. All living organisms are made of one or more cells. Cells come in two main types: prokaryotic (bacteria, no nucleus) and eukaryotic (plants, animals, fungi — with a true nucleus).\n\nEach organelle within a eukaryotic cell has a specialised role, and together they keep the cell alive and functioning. Understanding cell biology is the foundation for studying genetics, physiology, and disease.',
    keyPoints: [
      'Nucleus: stores genetic material (DNA) and controls cell activities',
      'Mitochondria: site of cellular respiration, produces ATP energy',
      'Ribosomes: site of protein synthesis',
      'Chloroplasts (plant cells only): site of photosynthesis',
      'Cell membrane: controls what enters and leaves the cell',
      'Plant cells have a cell wall, chloroplasts, and a large permanent vacuole — animal cells do not',
    ],
  },
  {
    id: 'rn-8',
    subjectId: 'sub-eng',
    topicId: 'top-shake',
    title: 'Shakespeare: Themes and Context',
    content:
      'William Shakespeare (1564–1616) is widely regarded as the greatest writer in the English language. His plays explore timeless themes — love, power, jealousy, ambition, and fate — through complex characters and innovative language.\n\nWhen analysing Shakespeare, it is important to consider both the literary techniques he uses and the historical and social context of Elizabethan and Jacobean England in which he wrote.',
    keyPoints: [
      'Shakespeare wrote 39 plays and 154 sonnets',
      'Three main categories: comedies, histories, and tragedies',
      'Common themes: ambition (Macbeth), jealousy (Othello), love (Romeo & Juliet)',
      'Iambic pentameter: ten syllables per line with alternating stress',
      'Dramatic irony: the audience knows more than the characters',
      'Soliloquies reveal a character\'s inner thoughts to the audience',
    ],
  },
];

export const practiceQuestions: PracticeQuestion[] = [
  {
    id: 'pq-1',
    subjectId: 'sub-math',
    topicId: 'top-algebra',
    question: 'Solve the simultaneous equations: 2x + y = 10 and x - y = 2',
    answer: 'From the second equation: x = y + 2. Substituting into the first: 2(y+2) + y = 10 → 2y + 4 + y = 10 → 3y = 6 → y = 2. Then x = 4. Solution: x = 4, y = 2.',
    difficulty: 'easy',
  },
  {
    id: 'pq-2',
    subjectId: 'sub-math',
    topicId: 'top-trig',
    question: 'In a right-angled triangle, the opposite side is 5cm and the hypotenuse is 13cm. What is sin(θ)?',
    answer: 'sin(θ) = opposite/hypotenuse = 5/13 ≈ 0.385. The angle θ ≈ 22.6°.',
    difficulty: 'easy',
  },
  {
    id: 'pq-3',
    subjectId: 'sub-math',
    topicId: 'top-calc',
    question: 'Differentiate f(x) = 3x⁴ - 2x² + 7x - 1',
    answer: 'Using the power rule: f\'(x) = 12x³ - 4x + 7. The constant -1 differentiates to 0.',
    difficulty: 'medium',
  },
  {
    id: 'pq-4',
    subjectId: 'sub-phys',
    topicId: 'top-mech',
    question: 'A car accelerates from rest at 2 m/s² for 10 seconds. What is its final velocity and how far does it travel?',
    answer: 'v = u + at = 0 + 2×10 = 20 m/s. Distance: s = ut + ½at² = 0 + ½×2×100 = 100 m. Final velocity: 20 m/s, Distance: 100 m.',
    difficulty: 'medium',
  },
  {
    id: 'pq-5',
    subjectId: 'sub-phys',
    topicId: 'top-elec',
    question: 'A circuit has a 12V battery and a 4Ω resistor. What current flows through the circuit?',
    answer: 'Using Ohm\'s Law: I = V/R = 12/4 = 3 A. A current of 3 amperes flows through the circuit.',
    difficulty: 'easy',
  },
  {
    id: 'pq-6',
    subjectId: 'sub-chem',
    topicId: 'top-atomic',
    question: 'An atom has 11 protons, 12 neutrons, and 11 electrons. What is its atomic number, mass number, and which element is it?',
    answer: 'Atomic number = 11 (number of protons), which is Sodium (Na). Mass number = 11 + 12 = 23. The element is sodium-23.',
    difficulty: 'easy',
  },
  {
    id: 'pq-7',
    subjectId: 'sub-chem',
    topicId: 'top-bonding',
    question: 'Explain why sodium chloride (NaCl) has a higher melting point than carbon dioxide (CO₂).',
    answer: 'NaCl has ionic bonding with strong electrostatic attraction between oppositely charged ions, requiring lots of energy to break. CO₂ has simple covalent bonding with weak intermolecular forces between molecules, so little energy is needed to separate them.',
    difficulty: 'medium',
  },
  {
    id: 'pq-8',
    subjectId: 'sub-bio',
    topicId: 'top-cells',
    question: 'Name three differences between plant and animal cells.',
    answer: '1) Plant cells have a cell wall (cellulose), animal cells do not. 2) Plant cells have chloroplasts for photosynthesis, animal cells do not. 3) Plant cells have a large permanent vacuole, animal cells have small temporary vacuoles or none.',
    difficulty: 'easy',
  },
];

export const savedResources: SavedResource[] = [
  {
    id: 'sr-1',
    type: 'note',
    refId: 'rn-1',
    subjectId: 'sub-math',
    title: 'Algebra: Key Rules and Formulas',
    savedAt: dateOffset(-2),
  },
  {
    id: 'sr-2',
    type: 'note',
    refId: 'rn-3',
    subjectId: 'sub-phys',
    title: 'Newton\'s Laws of Motion',
    savedAt: dateOffset(-4),
  },
  {
    id: 'sr-3',
    type: 'question',
    refId: 'pq-4',
    subjectId: 'sub-phys',
    title: 'Car acceleration problem',
    savedAt: dateOffset(-1),
  },
];
